# =============================
# CONFIGURACIÓN DE PRODUCCIÓN
#
# Este archivo contiene propiedades específicas para el entorno de producción.
# Aquí se debe usar 'spring.jpa.hibernate.ddl-auto=validate' o 'none'.
# NUNCA uses 'update' en producción para evitar cambios accidentales en la base de datos.
# =============================
spring.jpa.hibernate.ddl-auto=validate 