# =============================
# CONFIGURACIÓN DE DESARROLLO
#
# Este archivo contiene propiedades específicas para el entorno de desarrollo.
# Aquí se permite 'spring.jpa.hibernate.ddl-auto=update' para facilitar el desarrollo.
# NUNCA uses este archivo ni esta configuración en producción.
# =============================
spring.jpa.hibernate.ddl-auto=update 