# --- Configuración del servidor ---
server.port=8080

# --- Configuración de perfiles (elige uno al arrancar) ---
spring.profiles.active=mem

# --- Configuración común de JPA ---
#spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.format_sql=true
#spring.jpa.defer-datasource-initialization=true

# --- Configuración de seguridad ---
#jwt.secret.key=${JWT_SECRET_KEY:clave_super_secreta_123}

# --- Configuración de logging ---
logging.level.org.springframework=INFO
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} %-5level %logger{36} - %msg%n

# --- Configuración de codificación ---
spring.mandatory-file-encoding=UTF-8
server.servlet.encoding.charset=UTF-8
server.servlet.encoding.enabled=true

# --- Otras configuraciones ---
spring.jackson.time-zone=Europe/Madrid
spring.jackson.locale=es_ES

# Permitir referencias circulares de beans (solo para demo/corrección)
spring.main.allow-circular-references=true